### ISSUE TITLE
DAV:creationdate

### ISSUE THREAD

**Issue by marinofaggiana** [icewind1991/SearchDAV#3]
Hi @icewind1991, it's very important implement the d:cretiondate for the webDAV, I have several issue with the search without this possibility ... 

It's possible ?

Thanks

**Comment by icewind1991** [comment]
Nextcloud doesn't keep track of creationdate so there is no way to expose it over webdav

**Comment by MorrisJobke** [comment]
> Nextcloud doesn't keep track of creationdate so there is no way to expose it over webdav

Then maybe collect it? ;)
