### ISSUE TITLE
SabreDAV 4.x

### ISSUE THREAD

**Issue by L3o-pold** [icewind1991/SearchDAV#9]
Support new version of SabreDAV https://github.com/sabre-io/dav/releases

**Comment by skjnldsv** [comment]
ping @icewind1991 :)

**Comment by L3o-pold** [comment]
@icewind1991 could we know why you closed it?

**Comment by skjnldsv** [comment]
@L3o-pold https://github.com/icewind1991/SearchDAV/commit/49c010f4d7c32724d564b0558361e3e2677f0909
